spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
spaceflight:
  url: "https://test.spaceflightnewsapi.net/api/v2/articles"
